### PR TITLE
fix problems about the config. fix JENKINS-37192

### PR DESCRIPTION
**Pull request by hidekiy**

### CODE REVIEW

**Comment by hidekiy** [comment]
@jieryn
How about this?

**Comment by jieryn** [comment]
Looks good, you should merge it. :)

**Comment by hidekiy** [comment]
@jieryn 
Thanks for your reviewing.
But I couldn't merge because I don't have write permission to this repository 😕

**Comment by Vermyndax** [comment]
Hi there. Is this repo no longer maintained? I have a requirement to implement HSTS and we're doing it with a container on AWS ECS. A plugin might solve the problem, but when we enabled the plugin it killed our container.

**Pull request merged**
